// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7pdPmeK-StsQQpy0-wsC4HHF0Ysy3Jg4',
    appId: '1:1076735938183:web:7236accea5040ce4a27222',
    messagingSenderId: '1076735938183',
    projectId: 'action-inc-taxi-app',
    authDomain: 'action-inc-taxi-app.firebaseapp.com',
    storageBucket: 'action-inc-taxi-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDMump_wQp15lxo9PA1fcKywU5ROF5-V8',
    appId: '1:1076735938183:android:552fca797e20fe74a27222',
    messagingSenderId: '1076735938183',
    projectId: 'action-inc-taxi-app',
    storageBucket: 'action-inc-taxi-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJlB-vyzdfqz9wZoe5fdB4pSFpb23S5A',
    appId: '1:1076735938183:ios:e9b68db89945fa5da27222',
    messagingSenderId: '1076735938183',
    projectId: 'action-inc-taxi-app',
    storageBucket: 'action-inc-taxi-app.appspot.com',
    iosBundleId: 'com.example.actionIncTaxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxJlB-vyzdfqz9wZoe5fdB4pSFpb23S5A',
    appId: '1:1076735938183:ios:e9b68db89945fa5da27222',
    messagingSenderId: '1076735938183',
    projectId: 'action-inc-taxi-app',
    storageBucket: 'action-inc-taxi-app.appspot.com',
    iosBundleId: 'com.example.actionIncTaxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7pdPmeK-StsQQpy0-wsC4HHF0Ysy3Jg4',
    appId: '1:1076735938183:web:3ed4cc864814f259a27222',
    messagingSenderId: '1076735938183',
    projectId: 'action-inc-taxi-app',
    authDomain: 'action-inc-taxi-app.firebaseapp.com',
    storageBucket: 'action-inc-taxi-app.appspot.com',
  );
}
